declare const styles: {
	readonly alert: string;
	readonly banner: string;
	readonly emptyState: string;
	readonly emptyStateActions: string;
	readonly emptyStateBody: string;
	readonly emptyStateDescription: string;
	readonly emptyStateEyebrow: string;
	readonly emptyStateIcon: string;
	readonly emptyStateRail: string;
	readonly emptyStateTitle: string;
	readonly feedbackActions: string;
	readonly feedbackContent: string;
	readonly feedbackDescription: string;
	readonly feedbackPanel: string;
	readonly feedbackTitle: string;
	readonly loader: string;
	readonly rangeHeader: string;
	readonly rangeIndicator: string;
	readonly rangeLabel: string;
	readonly rangeRoot: string;
	readonly rangeTrack: string;
	readonly rangeValue: string;
	readonly skeleton: string;
	readonly spinner: string;
	readonly toastAction: string;
	readonly toastClose: string;
	readonly toastContent: string;
	readonly toastDescription: string;
	readonly toastRoot: string;
	readonly toastSignal: string;
	readonly toastTitle: string;
	readonly toastViewport: string;
};

export default styles;
